module.exports = {
  DATA_SCHEME: process.env.DATA_SCHEME,
  DATA_DOMAIN: process.env.DATA_DOMAIN,
  HASURA_GRAPHQL_ADMIN_SECRET: process.env.HASURA_GRAPHQL_ADMIN_SECRET,
  HASURA_CLIENT_NAME: process.env.HASURA_CLIENT_NAME,
};
